#!/usr/bin/python
from Bio import SeqIO
from sys import argv
input_fh=open(argv[1],'rU')
for record in SeqIO.parse(input_fh,"fasta"):
	print ">"+str(record.id)	
	sequence=str(record.seq)
	print sequence[int(argv[2]):int(argv[3])]
